name: fifa21
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_modular: ^5.0.3
  asuka: ^2.0.1+3
  lottie: ^2.0.0
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/image-icons/
